### ISSUE TITLE
Good start!  Now...

### ISSUE THREAD

**Issue by digitalchaotics** [jamesrisberg/XChangeTester#1]
1. Create an account at Liqui.io
2. Generate API keys and plug them into the appropriate spot
3. Call each API method for the three Services
4. See what each method returns, or what exceptions it throws (if any)
5. Log the results here

**Comment by jamesrisberg** [comment]
******************  Market Data Service Tests!  ******************


Trying liquiMarketDataService.getTicker(CurrencyPair.ETH_BTC)

Success! Result:
Ticker [currencyPair=ETH/BTC, open=null, last=0.09141918, bid=0.09142832, ask=0.09163783, high=0.09716276, low=0.0910447,avg=null, volume=85.4001014497284563, quoteVolume=null, timestamp=1518745836]


----------------------------------------------------------------------


Trying liquiMarketDataService.getOrderBook(CurrencyPair.ETH_BTC)

Success! Result:
OrderBook [timestamp: null, asks=[LimitOrder [limitPrice=0.09163783, Order [type=ASK, originalAmount=0.5232654, cumulativeAmount=0, averagePrice=0, currencyPair=ETH/BTC, id=, timestamp=null, status=PENDING_NEW]], LimitOrder [limitPrice=0.091647, Order [type=ASK, originalAmount=0.00497699, cumulativeAmount=0, averagePrice=0, currencyPair=ETH/BTC, id=, timestamp=null, status=PENDING_NEW]], LimitOrder [limitPrice=0.0920738, Order [type=ASK, originalAmount=0.32751091, cumulativeAmount=0, averagePrice=0, currencyPair=ETH/BTC, id=, timestamp=null, status=PENDING_NEW]], LimitOrder [limitPrice=0.09210633, Order [type=ASK, originalAmount=0.2494384, cumulativeAmount=0, averagePrice=0, currencyPair=ETH/BTC, id=, timestamp=null, status=PENDING_NEW]], LimitOrder [limitPrice=0.09220633, Order [type=ASK, originalAmount=0.52824141, cumulativeAmount=0, averagePrice=0, currencyPair=ETH/BTC, id=, timestamp=null, status=PENDING_NEW]], LimitOrde... (shortened for sanity)


----------------------------------------------------------------------


Trying liquiMarketDataService.getTrades(CurrencyPair.ETH_BTC)

Success! Result:
Trades
lastID= 0
[trade=Trade [type=BID, originalAmount=0.04588839, currencyPair=ETH/BTC, price=0.09538479, timestamp=Thu Feb 15 03:36:49 PST 2018, id=71556646]]
[trade=Trade [type=BID, originalAmount=0.03555109, currencyPair=ETH/BTC, price=0.09539474, timestamp=Thu Feb 15 03:37:00 PST 2018, id=71556696]]
[trade=Trade [type=BID, originalAmount=0.00524137, currencyPair=ETH/BTC, price=0.09539474, timestamp=Thu Feb 15 03:37:00 PST 2018, id=71556695]]
[trade=Trade [type=BID, originalAmount=0.0655673, currencyPair=ETH/BTC, ... (shortened for sanity)



----------------------------------------------------------------------


******************  Account Service Tests!  ******************


Trying liquiAccountService.getAccountInfo()

NotAvailableFromExchangeException Requested Information from Exchange is not available.
NotAvailableFromExchangeException Requested Information from Exchange is not available.
NotAvailableFromExchangeException Requested Information from Exchange is not available.
Success! Result:
AccountInfo [username=null, tradingFee=null, wallets={Liqui wallet=Wallet [id=Liqui wallet... (shortened for sanity)


----------------------------------------------------------------------


Trying liquiAccountService.withdrawFunds(Currency.BTC, new BigDecimal(0.01), "ADDRESS")

Trying liquiAccountService.requestDepositAddress(Currency.BTC)

Trying liquiAccountService.getFundingHistory(tradeHistoryParams)

******************  Trade Service Tests!  ******************


Trying liquiTradeService.getOpenOrders()

NotAvailableFromExchangeException Requested Information from Exchange is not available.
Success! Result:
Open orders: None
Hidden orders: None



----------------------------------------------------------------------


Trying liquiTradeService.placeMarketOrder(marketOrder)

Trying liquiTradeService.placeLimitOrder(limitOrder)

LiquiException invalid parameter: pair
Trying liquiTradeService.placeStopOrder(stopOrder)
NotYetImplementedForExchangeException Feature not yet implemented for exchange.

Trying liquiTradeService.cancelOrder(orderID)

[main] WARN org.knowm.xchange.liqui.service.LiquiTradeService - Unable to cancel order(1).
org.knowm.xchange.liqui.dto.LiquiException: Order with id 1 was not found.
	at org.knowm.xchange.liqui.service.LiquiBaseService.checkResult(LiquiBaseService.java:37)
	at org.knowm.xchange.liqui.service.LiquiTradeServiceRaw.cancelOrder(LiquiTradeServiceRaw.java:47)
	at org.knowm.xchange.liqui.service.LiquiTradeService.cancelOrder(LiquiTradeService.java:67)
	at ExchangeTester.testTradeService(ExchangeTester.java:323)
	at ExchangeTester.main(ExchangeTester.java:48)
Success! Result:
false


----------------------------------------------------------------------


Trying liquiTradeService.getTradeHistory(tradeHistoryParams)

Trying liquiTradeService.getOrder(orderIDs)

NullPointerException null
LiquiException invalid order

**Comment by jamesrisberg** [comment]
******************  Market Data Service Tests!  ******************


Trying liquiMarketDataService.getTicker(CurrencyPair.ETH_BTC)

Success! Result:
Ticker [currencyPair=ETH/BTC, open=null, last=0.09241419, bid=0.09229563, ask=0.09250724, high=0.09692341, low=0.0910447,avg=null, volume=83.038359452835352, quoteVolume=null, timestamp=1518748007]


----------------------------------------------------------------------


Trying liquiMarketDataService.getOrderBook(CurrencyPair.ETH_BTC)

Success! Result:
OrderBook [timestamp: null, asks=[LimitOrder [limitPrice=0.0925072...


----------------------------------------------------------------------


Trying liquiMarketDataService.getTrades(CurrencyPair.ETH_BTC)

Success! Result:
Trades
lastID= 0
[trade=Trade [type=BID, originalAmount=0.06514685, currencyPair=ETH/BTC...



----------------------------------------------------------------------


******************  Account Service Tests!  ******************


Trying liquiAccountService.getAccountInfo()

Success! Result:
AccountInfo [username=null, tradingFee=null, wallets={Liqui wallet=Wall...


----------------------------------------------------------------------


Trying liquiAccountService.withdrawFunds(Currency.BTC, new BigDecimal(0.01), "ADDRESS")

NotAvailableFromExchangeException Requested Information from Exchange is not available.


----------------------------------------------------------------------


Trying liquiAccountService.requestDepositAddress(Currency.BTC)

NotAvailableFromExchangeException Requested Information from Exchange is not available.


----------------------------------------------------------------------


Trying liquiAccountService.getFundingHistory(tradeHistoryParams)

NotAvailableFromExchangeException Requested Information from Exchange is not available.


----------------------------------------------------------------------


******************  Trade Service Tests!  ******************


Trying liquiTradeService.getOpenOrders()

Success! Result:
Open orders: None
Hidden orders: None



----------------------------------------------------------------------


Trying liquiTradeService.placeMarketOrder(marketOrder)

NotAvailableFromExchangeException Requested Information from Exchange is not available.


----------------------------------------------------------------------


Trying liquiTradeService.placeLimitOrder(limitOrder)

LiquiException invalid parameter: pair


----------------------------------------------------------------------


Trying liquiTradeService.placeStopOrder(stopOrder)

NotYetImplementedForExchangeException Feature not yet implemented for exchange.


----------------------------------------------------------------------


Trying liquiTradeService.cancelOrder(orderID)

[main] WARN org.knowm.xchange.liqui.service.LiquiTradeService - Unable to cancel order(1).
org.knowm.xchange.liqui.dto.LiquiException: Order with id 1 was not found.
	at org.knowm.xchange.liqui.service.LiquiBaseService.checkResult(LiquiBaseService.java:37)
	at org.knowm.xchange.liqui.service.LiquiTradeServiceRaw.cancelOrder(LiquiTradeServiceRaw.java:47)
	at org.knowm.xchange.liqui.service.LiquiTradeService.cancelOrder(LiquiTradeService.java:67)
	at ExchangeTester.testTradeService(ExchangeTester.java:334)
	at ExchangeTester.main(ExchangeTester.java:48)
Success! Result:
false


----------------------------------------------------------------------


Trying liquiTradeService.getTradeHistory(tradeHistoryParams)

NullPointerException null


----------------------------------------------------------------------


Trying liquiTradeService.getOrder(orderIDs)

LiquiException invalid order


----------------------------------------------------------------------
